name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Se connecter à EC2 et déployer
        uses: appleboy/ssh-action@v1.0.3
        env:
          RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: RDS_ENDPOINT,RDS_PASSWORD
          script: |
            cd infra-aws
            git pull
            mysql -h $RDS_ENDPOINT -u admin -p$RDS_PASSWORD devops_trainer < database/devops_trainer_data.sql
